# These are supported funding model platforms

patreon: kevinfaguiar
ko_fi: kevinfaveri
liberapay: kevinfaguiar
custom: ["https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=kevinfaveridev@gmail.com%20&lc=US&item_name=Donation%20for%20supporting%20@kevinfaguiar%20open%20source%20projects&no_note=0&cn=&currency_code=USD&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted", "https://www.blockchain.com/pt/btc/address/bc1q3ln0v73ketq3fzeh2saa2tsew4xmrwepdj42jw"]
